### ISSUE TITLE
Rmarkdown rendering error

### ISSUE THREAD

**Issue by rutujact** [CredibilityLab/groundhog#67] opened 2021-02-18 07:51 UTC
Hi Uri,

**Groundhog says Rmakrdown is attached. This is confirmed with sessionInfo()**
`sessionInfo() `
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rprojroot_1.3-2 bookdown_0.18   rmarkdown_2.1   groundhog_1.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4      digest_0.6.25   mime_0.9        backports_1.1.5 jsonlite_1.6.1 
 [6] magrittr_1.5    evaluate_0.14   highr_0.8       rlang_0.4.5     stringi_1.4.6  
[11] tools_3.6.3     stringr_1.4.0   glue_1.3.2      markdown_1.1    tinytex_0.20   
[16] xfun_0.12       yaml_2.2.1      compiler_3.6.3  base64enc_0.1-3 htmltools_0.4.0
[21] knitr_1.28

**But knitting Rmarkdown gives this error:**

`Error in loadNamespace(name) : there is no package called ‘rmarkdown’
Calls: :: ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted`

**Will this be fixed by the groundhog version update?**

**Comment by urisohn** [comment] 2021-02-18 08:09
Hi,
May need more info.
1) Is this an .rmd or .r file?
2) Can you include the code you used to load the packages and the command generating the error?

**Comment by rutujact** [comment] 2021-02-18 09:54
Hi,

1. Yes, this is a .rmd file.
2. Here is the code:
`groundhog::groundhog.library('rmarkdown', "2020-04-01")`
groundhog says: successfully loaded 'rmarkdown_2.1'.
`groundhog::groundhog.library('rprojroot', "2020-04-01")`
groundhog says: successfully loaded 'rprojroot_1.3-2'.

I then use Rstudio's knit button to knit the test .rmd file. By the way, it knits fine if I install 'rmakrdown' manually or allow Rstudio to do so. (I removed the other Rmarkdown version when I made these tests). 

By the way, when I manually install (or via Rstudio) 'rmakrdown' or any other packages, these packages show up under the "Packages" pane of RStudio under the *User Library*. But when groundhog installs rmakrdown or any other packages, they do not show up anywhere in the *Packages* pane. And neither do they show up under the installed.packages(). Is that normal? So apart from the message from groundhog that a package was 'successfully loaded', the only other validation of successful installation I have found is by using sessionInfo(). 

I thought this is strange because when I installed groundhog, the path it showed where it would store downloaded packages  was the same as that for the *User Library* (where for example, groundhog is downloaded). See below:

`install.packages("groundhog")`

> Installing package into ‘/Users/ftuser/Library/R/3.6/library’
> (as ‘lib’ is unspecified)
> trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/groundhog_1.2.0.tgz'
> Content type 'application/x-gzip' length 2121637 bytes (2.0 MB)
> ==================================================
> downloaded 2.0 MB

> The downloaded binary packages are in
> 	/var/folders/ct/szl65wyd613d80qcrfj206080000gs/T//RtmpKzS22o/downloaded_packages
> 

`library(groundhog)`

> Loaded 'groundhog' (version:1.2.0) using R-3.6.3
> Path to folder where downloaded packages are saved: '/Users/ftuser/Library/R/3.6/library'.
> To change its location: 'set.groundhog.folder(<path>)'
>      >>> If you encounter errors using groundhog: http://groundhogR.com/troubleshooting
>

**Comment by urisohn** [comment] 2021-02-18 10:35
I am not an R Studio expert nor do I use knitr, but, the problem is almost surely that when using R Studio it is loading and looking for packages separately from your R session. 

This makes R Studio a bit more user friendly, but a lot less version control friendly. (e.g., R Studio loads from your local library the package 'knitr' the moment you open an .rmd file, so you cannot control wich version of knitr it opens, nor ensure that when another person runs your script they will load the same version).

This does not seem fully solvable, as in, everything works as easily as it does now, but also with version control.
There are pretty good partial solutions though

Solution 1) Use version control for all packages except those involved in turning .r into .html or .pdf. That is, rely on R Studio and/or standard library commands to load knitr, markdown etc. So load all substantive packages with groundhog, and let R Studio do its thing for markdown, knitr

2) Instead of using an R Studio button to render the .html or .pdf, use an R command (one reason people use R instead of other point-and-click software, say SPSS or Excel) is that point-and-click is not reproducible, that includes R Studio...)
Running this command:
rmarkdown::render('example.Rmd','html_document')

That's ultimately what the button is running, but it is bypassing your local session to do it.

**Comment by rutujact** [comment] 2021-02-18 10:36
Hi, 

Turns out render works even when rmarkdown is installed via groundhog. 
Files are knit with both the commands below.
`render("test.rmd")`
`render("test.Rmd", output_format = "bookdown::html_document2")`

with the Rstudio Knit button, html_document is knit, but the format bookdown::html_document2 is not knit, as Rstudio does not recognize that bookdown is installed by groundhog. (Rstudio prompts me to install bookdown).

**Comment by urisohn** [comment] 2021-02-18 10:37
our messages crossed, right?

**Comment by alecristia** [comment] 2021-02-25 17:25
Hello all,

I'm not having the exact same issue (which seems solved) but a conceptually related one, in a way. Apologies if this is in the [vignette](https://rdrr.io/cran/groundhog/f/vignettes/groundhog.Rmd), which is throwing a "not found" error just now.

I've a set of rmd files that I've been using within RStudio, and would like to groundhog them. I've added in my setup chunk

> library(groundhog)
groundhog.day="2021-02-23"
pkgs=c('readr','kableExtra','bayestestR','brms','logspline','see')
groundhog.library(pkgs, groundhog.day)


Now I can no longer knit this with the knit button (if I try, something churns for a bit and then I get "Execution halted") and `rmarkdown::render("EL1000-6-z_confirmation copy.Rmd")` churns for a bit, I get the cursor back, but nothing else happens, and particularly no file is created.

Thank you in advance!

**Comment by urisohn** [comment] 2021-02-25 18:41
I would suggest trying
1) including rmarkdown in  `pkgs`  to ensure you are using a version of rmarkdown compatible with its dependencies
2) using library() instead of groundhog library to make sure this is an issue associated with using groundhog and not some other unrelated issue.

**Comment by rutujact** [comment] 2021-02-26 04:41
@alecristia When I used groundhog within the setup chunk, I had to groundhog each package separately. Then render knitted it fine.

**Comment by alecristia** [comment] 2021-02-26 17:54
thanks, @rutujact, I wouldn't have thought of trying that and it worked!

**Comment by urisohn** [comment] 2021-02-26 18:38
OK, I missed the similarity of the situation.
Glad @rutujact shared the solution. I thought it would only make a difference when sourcing, but i guess the 'setup chunk' (I don't use markdown so am not familiar) must have behavior like that of sourcing. 

The bug is an exit() in the loop which loads a set of packages, it breaks the original call and stops processing. 
That's why calling packages 1 by 1 does not show the problem. exit() is never called. 

The revised package does not call on exit() when the loop finishes, so this issue will be fixed.

**Comment by alecristia** [comment] 2021-03-04 09:20
thanks, @urisohn ! just fyi, I updated groundhog and I still need to call each package separately. Please DO ignore this message if you meant a future release will incorporate a fix.

**Comment by alecristia** [comment] 2021-03-04 16:38
@urisohn sorry to bother you again, what is the best way to install packages available from github?
e.g. [papaja](https://github.com/crsh/papaja)

```
devtools::install_github("crsh/papaja")
```

**Comment by urisohn** [comment] 2021-03-04 16:44
For now groundhog only works with CRAN.
To make github reproducible the package would need to be copied from github to a repository which does not allow changes. We may offer this in the future teaming up with ResearchBox to store packages not from CRAN in a permament repository;  but for now only CRAN.

(and about the previous point. Yes, I was referring to a forthcoming new version of groundhog, not yet available on CRAN)

**Comment by tjebo** [comment] 2021-03-04 18:51
Not necessarily related, but I wanted to leave a comment for future readers regarding the package incompatibility described on http://groundhogr.com/troubleshooting/ 

I found this actually very annoying and also dangerous, because RStudio / rmd seemed to load packages such as tibble which might make data handling really different in the future. 

Yet another solution to this is described in Stackoverflow: 
https://stackoverflow.com/questions/25962942/avoid-loading-data-every-time-in-knitr

I am now loading packages separately in a pure .R file, and then knitting the RMD document from within this file with `rmarkdown::render`. This is not a great solution, but it works.

**Closed** 2021-03-19 04:11 UTC
